//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumAutomation.RunSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class CRSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CRSettings defaultInstance = ((CRSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CRSettings())));
        
        public static CRSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
